### ISSUE TITLE
Updated version from 2.0.1 to 2.2.0 and now android app is not building

### ISSUE THREAD

**Issue by BunnyBuddy** [pusher/pusher-channels-flutter#130] opened 2023-09-08 10:26 UTC
We were using pusher_channels_flutter version 2.0.1 in our app, due to a crash issue which was resolved in 2.2.0 we updated the package but now it doesn't let the app build on Android. We get the following error,

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :pusher_channels_flutter.
     Required by:
         project :app
      > No matching configuration of project :pusher_channels_flutter was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.`

This is the result of Flutter Doctor,

`[✓] Flutter (Channel stable, 2.10.4, on macOS 12.6.8 21G725 darwin-x64, locale en-PK)
    • Flutter version 2.10.4 at /Users/macbookpro/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (1 year, 5 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Users/macbookpro/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile)    • emulator-5554             • android-x64    • Android 12 (API 31) (emulator)
    • iPhone (mobile) • 00008020-001D0D0A2E88003A • ios            • iOS 16.6 20G75
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 116.0.5845.179

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by BunnyBuddy** [comment] 2023-09-14 05:38
If I keep working with the old version, I get this error in the crash logs on playstore for Android 9 and Android 13 devices. 

Exception java.lang.NullPointerException:
  at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.callback (PusherChannelsFlutterPlugin.java)
  at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onConnectionStateChange (PusherChannelsFlutterPlugin.java)
  at com.pusher.client.connection.websocket.WebSocketConnection$4.run (WebSocketConnection.java)
  at com.pusher.client.util.Factory$1.run (Factory.java)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

**Comment by benjamin-tang-pusher** [comment] 2023-09-28 18:01
That NullPointerException should be fixed on 2.2.0, but I don't know why its not building for you. `Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.` looks like a Gradle build issue, but I cannot reproduce this.

As a quick experiment, can you generate a new flutter project, and import this library again? This will help isolate if the issue is with the project's Gradle.

**Comment by BunnyBuddy** [comment] 2024-01-26 07:42
I'll let you know..

**Comment by benw-pusher** [comment] 2024-03-26 16:19
We haven't had a response here so closing. If you need anything more please get in touch at https://messagebird.com/support-center/Pusher-request-new

**Closed by benw-pusher** 2024-03-26 16:19 UTC
