### ISSUE TITLE
FATAL EXCEPTION: pusher-java-client eventQueue

### ISSUE THREAD

**Issue by mohamedsalah414** [pusher/pusher-channels-flutter#53] opened 2022-07-21 10:20 UTC
Dear pusher team, 
release apk terminated when make subscribe pusher channel but working in debug mode
and this is an error in logcat from a real device

`2022-07-21 11:47:25.066 22028-22129/? E/AndroidRuntime: FATAL EXCEPTION: pusher-java-client eventQueue
    Process: com.coappso.gym_system, PID: ***28
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.i.d, parameter e
        at v4.c.a(Unknown Source:7)
        at y4.d.w(Unknown Source:12)
        at y4.d.i(Unknown Source:11)
        at y4.b.h(Unknown Source:30)
        at b5.b.w(Unknown Source:18)
        at b5.b.q(Unknown Source:0)
        at b5.b$f.run(Unknown Source:26)
        at d5.b$a.run(Unknown Source:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)`

**Comment by mohamedsalah414** [comment] 2022-07-25 07:40
> ###  FATAL EXCEPTION: pusher-java-client eventQueue
> ### java.lang.NullPointerException: Parameter specified as non-null is null

**Does anyone have a solution ???**

**Comment by benjamin-tang-pusher** [comment] 2022-07-29 13:19
Hi, can you paste your Pusher code here? Including your initialisation, connection and subscribe method calls

**Comment by mohamedsalah414** [comment] 2022-07-31 09:47
this Gradle version solves my problem
`dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
     

    }`

the error happens with gradle:7.1.2

**Comment by mohamedsalah414** [comment] 2022-08-02 07:29
`gradle:7.1.3`
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
```

**Comment by KristupasKuras** [comment] 2022-08-30 15:15
I'm having the same issue event with v2.0.1 :/ Any ideas?

**Comment by mohamedsalah414** [comment] 2022-08-31 08:47
> 

Downgrade gradle version to 4.1.0

**Comment by KristupasKuras** [comment] 2022-09-01 08:51
Unfortunately, this is not appropriate solution for me, as it clashes with other packages compatibility...

**Comment by Krispy145** [comment] 2022-09-05 14:57
@KristupasKuras Same here, Pusher team we really need a better solution then this!!!

**Comment by Akellacom** [comment] 2022-09-06 00:48
It worked like this for me:

**android/gradle/wrapper/gradle-wrapper.properties**
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.1-all.zip`

**android/build.gradle**
`classpath 'com.android.tools.build:gradle:4.1.0'`

**Comment by benjamin-tang-pusher** [comment] 2022-09-23 10:50
[Krispy145](https://github.com/Krispy145)'s comment https://github.com/pusher/pusher-channels-flutter/issues/53#issuecomment-1237245577 on setting `-keep class com.pusher.client.** { *; }` in proguard-rules.pro nudged me in the right direction. I'm convinced the issue is minifying (with R8 for example) our library is causing an issue likely related to https://github.com/pusher/pusher-websocket-java/issues/333.

Its strange, however, that setting android gradle plugin to 4.1.0 works around this. I think its affecting the minifying so it inadvertently works. Adding -keep class com.pusher.client.** { *; } also doesnt seem to fix it for me, instead it changes the error message to 

FATAL EXCEPTION: pusher-java-client eventQueue
Process: com.awesomeproject2, PID: 8625
java.lang.UnsupportedOperationException: k
at a4.h.f(Unknown Source:10)
at com.pusher.client.channel.PusherEvent.fromJson(Unknown Source:83)

This might be a red herring though, so I'm still looking at this.

**Comment by benjamin-tang-pusher** [comment] 2022-10-18 14:33
@Akellacom @KristupasKuras @mohamedsalah414 could you try adding the proguard setting file like Krispy145 suggested? I'm hesitant to close this issue since 3 of you reported it, but I haven't been able to reproduce this even though I'm sure I'm running a release build and subscribing to a private channel. I'm also using Flutter 3.3 with android gradle 7.1.2.

**Comment by benjamin-tang-pusher** [comment] 2022-10-26 09:20
I'm going to close this due to the lack of responses. If this was caused by minifying, then our new 2.4.4 [java websocket library](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/resources/META-INF/proguard/pusher.pro)  has narrower proguard keep rules to prevent this.

**Closed by benjamin-tang-pusher** 2022-10-26 09:20 UTC

**Comment by saurabhunify** [comment] 2022-11-09 10:46
This resolved my issue

> proguard-rules.pro
