### ISSUE TITLE
com.pusher.channels_flutter.PusherChannelsFlutterPlugin.callback crash android

### ISSUE THREAD

**Issue by No1Ks** [pusher/pusher-channels-flutter#91] opened 2022-12-26 07:46 UTC
PusherChannelsFlutterPlugin.java line 2

<img width="721" alt="image" src="https://user-images.githubusercontent.com/10095599/209519938-7b78faeb-0ba5-4405-a7fc-4e50635b1af0.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/10095599/209520180-2a659f5f-98e3-4102-a6ca-8b4f82848053.png">

I'm tired of this bug. And I can do nothing with this. Seems like it crashes when user collapsing app and status changing, or some message received. Please help me to fix this issue.

**Comment by Marcus-Oliveira** [comment] 2023-01-06 14:10
The same issue here, please someone help us

**Comment by philipguedes** [comment] 2023-01-06 20:22
same here

**Comment by No1Ks** [comment] 2023-01-07 06:26
I guess this is occured in result of using FragmentActivity instead of basic Activity. But I can't use the base one because of biometric auth package

**Comment by benjamin-tang-pusher** [comment] 2023-01-09 11:00
Has anyone else been able to reproduce this issues? @No1Ks , do you have a theory as to why this is related to FragmentActivity?

**Comment by No1Ks** [comment] 2023-01-09 11:21
I'm not really sure. I guess I saw a topic where FragmentActivity mentioned as related to this issue, when I was searching for this error couple of months ago

**Comment by Marcus-Oliveira** [comment] 2023-01-09 13:32
I'm using FlutterActivity instead of FragmentActivity. This my MainActivity.kt

```
class MainActivity: FlutterActivity(), OnMapsSdkInitializedCallback{
    override
    fun onCreate(savedInstanceState: Bundle?){
        super.onCreate(savedInstanceState)
        MapsInitializer.initialize(applicationContext, Renderer.LATEST, this)
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
            registerActivityLifecycleCallbacks(BrazeActivityLifecycleCallbackListener())
        }
    }

    override fun onMapsSdkInitialized(renderer: Renderer) {
        val rendererName = renderer.name.lowercase()
        Log.d("NewRendererLog", "The $rendererName version of the renderer is used.")
    }
}
```

**Comment by Gursewak-Uppal** [comment] 2023-01-12 03:18
Facing the same problem since a long time. I connected with pusher support team via email but no one replied.

**Comment by luisfelipeas5** [comment] 2023-01-16 12:49
Same problem here!

**Comment by rkuzmin** [comment] 2023-01-18 11:53
have same issue

**Comment by mursalov** [comment] 2023-01-18 11:58
I have the same issue, I am already using `FlutterActivity`, so that doesn't seem to be the workaround.

**Comment by benjamin-tang-pusher** [comment] 2023-01-23 10:54
Could you log the [connection state change](https://github.com/pusher/pusher-channels-flutter#onconnectionstatechange) and the [onError](https://github.com/pusher/pusher-channels-flutter#onerror) in your Crashylitics? I'd like to see what the library was doing.

**Comment by mursalov** [comment] 2023-01-23 11:06
@benjamin-tang-pusher `onConnectionStateChange` and `onError` methods are both using this same callback as well, so we are not able to receive the connection state or the error without the crash happening.
`// Event handlers
    override fun onConnectionStateChange(change: ConnectionStateChange) {
        callback(
            "onConnectionStateChange", mapOf(
                "previousState" to change.previousState.toString(),
                "currentState" to change.currentState.toString()
            )
        )
    }`

**Comment by mursalov** [comment] 2023-01-23 11:08
@benjamin-tang-pusher `onConnectionStateChange` and `onError` methods are both using this same callback as well, so we are not able to receive the connection state or the error without the crash happening.
`
// Event handlers
    override fun onConnectionStateChange(change: ConnectionStateChange) {
        callback(
            "onConnectionStateChange", mapOf(
                "previousState" to change.previousState.toString(),
                "currentState" to change.currentState.toString()
            )
        )
    }
`

**Comment by luisfelipeas5** [comment] 2023-01-26 11:48
Guys, using the #95 the crash reports of this issue stopped to be logged on crashlytics. But, our team don't understand why `activity` turn into `null` in the first place, so the root case is unkown yet, and this could be considered a workaround for now to avoid crash the app.

**Comment by benjamin-tang-pusher** [comment] 2023-03-13 20:00
https://github.com/pusher/pusher-channels-flutter/pull/95 was and the lib has been bumped up to 2.1.2. As @luisfelipeas5  has mentioned, please use this version which workaround the app crashing.

Is anyone able to determine if when this error occurs, your `pusher` instance stops (and you stop getting messages)?

**Comment by benjamin-tang-pusher** [comment] 2023-06-16 19:40
Just asking again, I understand that with this workaround `activity` can still be `null`, but has anyone noticed if their app stops receiving messages because of this?

**Comment by benjamin-tang-pusher** [comment] 2023-08-10 14:48
I will close this GH Issue since there hasn't been feedback for a couple of months. We also released a new version of of the flutter library v2.2.0, that fixed another issue that I suspect is related to this, I recommend everyone upgrade to this.

**Closed by benjamin-tang-pusher** 2023-08-10 14:48 UTC
