### ISSUE TITLE
javax.net.ssl.SSLException when pusher state changes to reconnecting

### ISSUE THREAD

**Issue by smalik02** [pusher/pusher-channels-flutter#39] opened 2022-04-15 15:23 UTC
Hi, we have been observing our log outputs through sentry, and this error keeps coming up 

`LOG: onError: An exception was thrown by the websocket code: null exception: javax.net.ssl.SSLException: Read error: ssl=0x8220a3b8: I/O error during system call, Software caused connection abort`

And it has been logged a couple of hundred times in production over the last 24 hrs or so. 

For context, here is our pusher.init function call and some of the event monitoring handlers. The issue seems to occur right after the connection state changes to `RECONNECTING`. 

```
Future setupPusher() async {
    try {
      await pusher.init(
          apiKey: '...',
          cluster: 'us3',
          onConnectionStateChange: onConnectionStateChange,
          onError: onError,
          useTLS: true,
          onSubscriptionSucceeded: onSubscriptionSucceeded,
          onSubscriptionError: onSubscriptionError,
          maxReconnectionAttempts: 20,
          maxReconnectGapInSeconds: 60,
          onAuthorizer: onAuthorizer);
    } catch (e) {
      log("ERROR: $e");
      await Sentry.captureException(e);
    }
  }

dynamic onAuthorizer(
      String channelName, String socketId, dynamic options) async {
    String token = await _authService.getTTToken();

    Response response = await post(
      Uri.parse('...'),
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        'Authorization': 'Bearer $token'
      },
      body: "socket_id=" + socketId + "&channel_name=" + channelName,
    );
    return json.decode(response.body);
  }

  Future onConnectionStateChange(
      dynamic currentState, dynamic previousState) async {
    log("Connection: $currentState");
    status = currentState;
    if (currentState == "DISCONNECTED") {
      await pusher.disconnect(); // force disconnect and then connect again
      await pusher.connect();
      // handle other services reset
    }
  }

  Future onError(String message, int code, dynamic e) async {
    log("onError: $message code: $code exception: $e");
    await Sentry.captureException(e);
  }

  void onSubscriptionSucceeded(String channelName, dynamic data) {
    log("onSubscriptionSucceeded: $channelName data: $data");
  }

  void onSubscriptionError(String message, dynamic e) {
    log("onSubscriptionError: $message Exception: $e");
  }
```

**Comment by smalik02** [comment] 2022-04-15 15:32
Another issue that pops when reconnecting is 

`An exception was thrown by the websocket code: null exception: java.net.UnknownHostException: Unable to resolve host "ws-us3.pusher.com": No address associated with hostname`

**Comment by benw-pusher** [comment] 2022-05-17 15:46
Sorry for the delay here. Are you still encountering this issue?

**Comment by smalik02** [comment] 2022-05-26 19:40
It went away for a bit, but just started to come back again. We went ahead and removed the manual disconnect as that might have prevented pusher from auto-reconnecting.

But unsure what's causing this recurring issue.

**Comment by benw-pusher** [comment] 2022-05-27 08:58
Thanks for the update - have you just now removed the manual disconnect/reconnect? I believe this may be a part of the issue - the error `Software caused connection abort` is typically caused by a process being interrupted - such as with a new connection attempt or an explicit disconnect call.

**Comment by benw-pusher** [comment] 2022-06-17 13:22
I haven't had a response for three weeks so I will close this out - if you are still having issues feel free to reopen or get in touch via https://support.pusher.com/hc/en-us/requests/new

**Closed by benw-pusher** 2022-06-17 13:22 UTC
