### ISSUE TITLE
How do i detect if pusher has already been initialized.

### ISSUE THREAD

**Issue by demola33** [pusher/pusher-channels-flutter#38] opened 2022-04-14 17:03 UTC
I keep getting a platform exception on android that pusher has already been initialized.

**Comment by Natanchik89** [comment] 2022-04-18 07:05
Hello, did you solve the problem?

**Comment by benjamin-tang-pusher** [comment] 2022-04-20 21:29
Can you paste the error message and the stacktrace?

Could you also provide more information on how to reproduce this? Normally you not be getting this exception.

**Comment by demola33** [comment] 2022-04-25 17:14
**This happens when i hot restart my Flutter application**

`E/MethodChannel#pusher_channels_flutter( 6421): Failed to handle method call
E/MethodChannel#pusher_channels_flutter( 6421): java.lang.IllegalArgumentException: Already subscribed to a channel with name trade-updates
E/MethodChannel#pusher_channels_flutter( 6421):         at com.pusher.client.channel.impl.ChannelManager.validateArgumentsAndBindEvents(ChannelManager.java:198)
E/MethodChannel#pusher_channels_flutter( 6421):         at com.pusher.client.channel.impl.ChannelManager.subscribeTo(ChannelManager.java:85)
E/MethodChannel#pusher_channels_flutter( 6421):         at com.pusher.client.Pusher.subscribe(Pusher.java:246)
E/MethodChannel#pusher_channels_flutter( 6421):         at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.subscribe(PusherChannelsFlutterPlugin.kt:150)
E/MethodChannel#pusher_channels_flutter( 6421):         at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onMethodCall(PusherChannelsFlutterPlugin.kt:68)
E/MethodChannel#pusher_channels_flutter( 6421):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#pusher_channels_flutter( 6421):         at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#pusher_channels_flutter( 6421):         at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#pusher_channels_flutter( 6421):         at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#pusher_channels_flutter( 6421):         at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#pusher_channels_flutter( 6421):         at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#pusher_channels_flutter( 6421):         at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#pusher_channels_flutter( 6421):         at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#pusher_channels_flutter( 6421):         at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#pusher_channels_flutter( 6421):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#pusher_channels_flutter( 6421):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter ( 6421): Pusher ERR: PlatformException(PusherChannelsFlutter, Pusher Channels already initialized., null, null)`

### This is my root class where i make calls to initialize pusher  and also connect to pusher ###
     @override
      void initState() {
        _getInitialUser();
        **resultLoaded = _initializeApp();**
        super.initState();
      }
    
      Future<void> _initializeApp() async {
        Future.delayed(const Duration(seconds: 4)).then((value) {
          **_pusherService.initializePusher();**
          return _auth.checkAndUpdateAuthStatus();
        });
      }

    @override
      Widget build(BuildContext context) {
        return ChangeNotifierProvider<AuthProvider>(
          create: (context) => locator<AuthProvider>(),
          child: Selector<AuthProvider, AuthState>(
            selector: (_, auth) => auth.appState,
            builder: (context, authState, child) => ScreenUtilInit(
              designSize: const Size(392.7, 737.4),
              minTextAdapt: true,
              builder: () {
                authState.maybeMap(
                  orElse: () {},
                  authenticated: (_) async {
                    **_pusherService.connect();**
                    _appRouter.pushAndPopUntil(const HomeRoute(),
                        predicate: (route) => false);
                  },
                  unauthenticated: (_) async {
                    _appRouter.pushAndPopUntil(const WelcomeScreen(),
                        predicate: (route) => false);
                    **await _pusherService.disconnect();**
                  },
                );

    **These methods are inside my Pusher class **
   ** on hot restart my initialized method is called again and i get that stack trace.

    Future<void> initializePusher() async {
    void onConnectionStateChange(String currentState, String previousState) {
    }

    void onError(String message, int? code, dynamic e) {
    }

    try {
      await Future.wait([
        _pusher.init(
          apiKey: appKey,
          cluster: cluster,
          logToConsole: true,
          onConnectionStateChange: onConnectionStateChange,
          onError: (message, code, error) {
            print("errMsg:$message");
            print("errCode:$code");
            print("err:$error");
            return;
          },
          onSubscriptionSucceeded: (channelName, data) {
            print("Subscribed to $channelName");
            print("data: $data");
          },
          onSubscriptionError: (message, error) =>
              print("OnSubErr" + error + " " + message),
        ),
        _subscribe(),
      ]);
      } catch (e) {
      print("Pusher ERR: $e");
     }
    }

     Future<void> connect() async {
      final connectionState = _pusher.connectionState;
      print("CSTATE: $connectionState");
      if (connectionState != "CONNECTED") {
        print("Connecting to pusher");
        await _pusher.connect();
      }

**Comment by proggen-com** [comment] 2022-05-10 13:41
You can do the same check as in your connect() function?

```
if (pusher.connectionState != "CONNECTED") {
  await _pusher.init( ... );
}
```

**Comment by Natanchik89** [comment] 2022-05-30 10:47
@proggen-com 
Hello, I have a pusher initialization when logging into the system, there is also a "pusher.disconnect ()" when logout. When I reauthorize my pusher.connectionState == DISCONNECTED and still I get "ERROR: PlatformException(PusherChannelsFlutter, Pusher Channels already initialized., null, null)"

**Comment by Natanchik89** [comment] 2022-06-15 03:34
@benw-pusher function Login 

`void _login() async{
    setState(() {
      _isLoading = true;
    });
    var data = {
      'email' : email,
      'password' : password
    };

    var res = await Network().authData(data, '/login');

    var body = json.decode(res.body);
    if(body['success']){
      SharedPreferences localStorage = await SharedPreferences.getInstance();
      localStorage.setString('token', body['token']);
      localStorage.setString('user', body['user_name']);
      Navigator.push(
        context,
        new MaterialPageRoute(
            builder: (context) => Home()
        ),
      );
    }else{
      _showMsg(body['message']);
    }

    setState(() {
      _isLoading = false;
    });
  }`

Class Home and init pusher

`class _HomeState extends State<Home>{
  PusherChannelsFlutter pusher = PusherChannelsFlutter.getInstance();
  String _log = 'output:\n';
  final _listViewController = ScrollController();
  var name, _socketId;
  @override
  void initState(){
    _loadUserData();
    _initPusher();
    super.initState();
  }

  _loadUserData() async{
    SharedPreferences localStorage = await SharedPreferences.getInstance();
    var user = localStorage.getString('user');
    if(user != null) {
      setState(() {
        name = user;
      });
    }
  }
  
  _initPusher() async{
    print(pusher.connectionState); // this == DISCONNECTED 
    try {
      if (pusher.connectionState != "CONNECTED") {
        await pusher.init(
            apiKey: apiKey,
            cluster: 'ap1',
            onConnectionStateChange: onConnectionStateChange,
            onError: onError,
            onSubscriptionSucceeded: onSubscriptionSucceeded,
            onEvent: onEvent,
            onAuthorizer: onAuthorizer
        );
      }
      await pusher.subscribe(channelName: 'presence-api-channel');
      await pusher.connect();
    } catch (e) {
      print("ERROR: $e");
    }
  }` 

function Logout

`void logout() async{
    await pusher.disconnect();
    var res = await Network().logoutApi('/logout');
    var body = json.decode(res.body);
    if(body['success']){
      SharedPreferences localStorage = await SharedPreferences.getInstance();
      localStorage.remove('user');
      localStorage.remove('token');
      Navigator.push(
          context,
          MaterialPageRoute(builder: (context)=>Login()));
    }
  }`

**Comment by Natanchik89** [comment] 2022-06-15 03:34
@benw-pusher After the first round (login, pusher initialization and logout) upon re-login, the pusher is already initialized and although pusher.connectionState = "DISCONNECTED ", the connection state implies that the busher has already been initiated, so the check is meaningless. How to check exactly the initialization or destroy it on logout?

**Comment by GauravCalidig** [comment] 2022-06-22 11:54
@benjamin-tang-pusher Any Ideas?

**Comment by Natanchik89** [comment] 2022-06-22 13:36
@GauravCalidig  You have a problem in the next stage after initialization, that is, in subscribe to the channel, and we have it in initialization. Or I misunderstood. Here is my error
![screen](https://user-images.githubusercontent.com/35212497/175042536-e55b48d1-226d-48a2-8207-8b43c24ed8b5.PNG)
:

**Comment by Natanchik89** [comment] 2022-06-23 09:24
[Did it help someone?](https://stackoverflow.com/questions/72301220/flutterpusherchannelsflutter-pusher-channels-already-initialized-null-null)

**Comment by benjamin-tang-pusher** [comment] 2022-06-27 18:50
I can reproduce this; I will ask around and find out why this is.

**Comment by JimmyTai** [comment] 2022-07-25 19:37
The root cause is dart vm restart after hot-restart but plugin not. 

https://github.com/flutter/flutter/issues/10437 
For now, we couldn’t be informed hot-restart is coming. Maybe we could check the init parameters in native side to decide whether re-initialize a PusherClient or reuse it rather than throw an exception. And move initialized check to dart side.

**Comment by SniffyMcTasty** [comment] 2022-08-29 15:58
I think I might have some new information about that problem.

Since the `getInstance()` method is static, I just put it in my main, which resolved the error when loading the screen that tries to make a connection to Pusher. However, it did not solve it whenever I was popping the screen and pushing it back. Because of this, I tried putting my `init(apiKey : {apiKey}, cluster {cluster})` into my main too, but then whenever I tried hot restarting the app, it showed me this error:

```
I/PusherChannelsFlutter(11358): Start com.pusher.client.Pusher@4ce4e43
W/System.err(11358): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err(11358): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err(11358): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I never saw this thing in my entire life, but I'm pretty sure it has something to do with the fact that the `_instance` variable is static to the class. I would suggest taking a look at the SharedPreferences package at https://github.com/flutter/plugins/tree/main/packages/shared_preferences/shared_preferences, as it also uses that static instance, but I have no problem making a custom class like the following and calling the `initSharedPreferences()` method in my main before even calling `runApp()`:

```dart
class SharedPreferencesController {
  static late SharedPreferences sharedPreferences;

  static Future<void> initSharedPreferences() async =>
      sharedPreferences = await SharedPreferences.getInstance();

  String get token => sharedPreferences.getString('token') ?? '';

  set token(String newToken) => sharedPreferences.setString('token', newToken);

  int get companyId => sharedPreferences.getInt('companyId') ?? 0;

  set companyId(int companyId) =>
      sharedPreferences.setInt('companyId', companyId);
}
```

**Comment by RootSoft** [comment] 2022-09-04 21:37
@JimmyTai @benjamin-tang-pusher Any updates on this? This has been a pain in the ass when developing.

Maybe a `dispose` method that can be called before initialization after a hot reload which cleans up the resources?

**Comment by diego-lipinski-de-castro** [comment] 2022-10-27 18:43
6 months...wow, did you guys move to another package?

**Comment by proggen-com** [comment] 2022-10-28 05:59
We have just merged https://github.com/pusher/pusher-channels-flutter/pull/80 which allow for re-initialization. Does that help in your case?

**Closed** 2023-02-07 14:21 UTC
